### ISSUE TITLE
Using absolute links as anchors leads to error message

### ISSUE THREAD

**Issue by MariusRumpf** [jellekralt/Responsive-Tabs#82] opened 2015-10-20 14:51 UTC
When using a tags with absolute links like:

```html
<a href="/help/#first-steps">First Steps</a>
```

the plugin throws an error `Uncaught Error: Syntax error, unrecognized expression: /help/#first-steps` from the plugin command `panelSelector = $anchor.attr('href');` in method `_loadElements()`.

**Comment by jellekralt** [comment] 2015-12-10 20:18
I cant seem to reproduce this issue, could you maybe create a jsbin example?

**Comment by jellekralt** [comment] 2016-02-15 20:04
Closing this due to lack of a reply, feel free to re-open if you still feel this is an issue!

**Closed by jellekralt** 2016-02-15 20:04 UTC
