### ISSUE TITLE
Multiple Tabs Open

### ISSUE THREAD

**Issue by coxrichuk** [jellekralt/Responsive-Tabs#71] opened 2015-07-28 16:20 UTC
Is there a way when in Accordion mode to have multiple tabs / panels open on first load?

If this isn't available I am happy to put a pull request into facilitate this.

I guess the best way would be to pass an array to `active` similar to `disabled` ?

**Comment by jellekralt** [comment] 2015-08-06 19:21
Currently, this is not supported. I'd be happy to accept a pull request though! Off the top of my head I think the ```_getStartTab``` function would need some work and the places where the function is called.

**Comment by jellekralt** [comment] 2015-08-09 12:27
Also, this relates to #40

**Comment by jellekralt** [comment] 2016-04-12 20:04
Closing this as a duplicate of #40

**Closed by jellekralt** 2016-04-12 20:04 UTC
Labels: enhancement
