### ISSUE TITLE
Stop tabs from being deactivated

### ISSUE THREAD

**Issue by tanc** [jellekralt/Responsive-Tabs#112] opened 2016-08-22 12:13 UTC
I'd like to be able to stop an active tab from being deactivated. Is there a setting for this?

You can see the behaviour on http://www.landcoalition.org/en/resources if you expand the filters and then click on a tab twice. It will toggle between active and inactive states which is odd as the collapsing of the panel has been disabled for tabs.

**Comment by jellekralt** [comment] 2016-11-08 21:48
The tabs shouldt be deactivated, and I can't reproduce this in my demo. I can see the thing happening on your page, could you share your configuration?

**Comment by tanc** [comment] 2016-11-09 09:56
Hi, thanks for getting back to me. My config is:
```javascript
wrapper.responsiveTabs({
  startCollapsed: 'accordion',
  collapsible: 'accordion',
  animation: false,
  animationQueue: true,
  duration: 200,
  active: 0
});
```

**Comment by jellekralt** [comment] 2017-03-27 12:06
Weird, I've tried your exact config, and for some reason I still cant reproduce this.. It feels like there is something on your website that is interfering with this. Unfortunately I don't have any time to dive more deeply into this..

**Comment by tanc** [comment] 2017-03-27 12:27
No problem, thanks for looking though!

**Comment by jellekralt** [comment] 2017-05-30 07:27
You're welcome! I'm going to close the issue for now, as I can't properly reproduce this with a clean project. If you run into the issue again with a different setup or have a clean example for me, feel free to reopen :)

**Closed by jellekralt** 2017-05-30 07:27 UTC
