### ISSUE TITLE
Is it possible that the previous accordion tab does not close when you click to another (on mobile)?

### ISSUE THREAD

**Issue by silviaRe** [jellekralt/Responsive-Tabs#62] opened 2015-05-28 13:38 UTC
Hi. As the title says, I want that the previous accordion tab does not close when I click on another tab.

It should only close when I click again on the opened accordion tab.

Is this posssible?

**Comment by jellekralt** [comment] 2015-08-06 19:37
Hi there,
Currently, this is not possible. I think it would be a good feature though. If I have time, i'll see if I can work it in. If you would like to build it yourself and submit a pull request, i'd be happy to accept it. :)

**Comment by jellekralt** [comment] 2015-08-09 12:27
I'm going to close this because it's a duplicate of #40

**Closed by jellekralt** 2015-08-09 12:27 UTC
Labels: duplicate
